services:
  mysql:
    image: mysql:8.0
    container_name: geeks-mysql
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: geeks
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - geeks-mysql-data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-uroot']
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  geeks-mysql-data:
